import Foundation
struct Question {
    let question: String
    let answers: [String]
    let correct: String
}

let quizCasinosVancouver = [
    Question(question: "Which is the largest casino in Vancouver?",
             answers: ["Grand Villa Casino", "Parq Vancouver", "Hard Rock Casino Vancouver", "River Rock Casino Resort"],
             correct: "Parq Vancouver"),
    Question(question: "Which Vancouver casino is known for its luxury hotel and fine dining restaurants?",
             answers: ["Parq Vancouver", "River Rock Casino Resort", "Grand Villa Casino", "Starlight Casino"],
             correct: "Parq Vancouver"),
    Question(question: "Which casino is located near Vancouver International Airport?",
             answers: ["Parq Vancouver", "Starlight Casino", "River Rock Casino Resort", "Grand Villa Casino"],
             correct: "River Rock Casino Resort"),
    Question(question: "Which casino in Vancouver features a rooftop park and two hotels?",
             answers: ["Starlight Casino", "Parq Vancouver", "Hard Rock Casino Vancouver", "Grand Villa Casino"],
             correct: "Parq Vancouver"),
    Question(question: "Which casino offers a famous buffet and live entertainment?",
             answers: ["River Rock Casino Resort", "Starlight Casino", "Grand Villa Casino", "Parq Vancouver"],
             correct: "River Rock Casino Resort"),
    Question(question: "Which casino in Vancouver has a partnership with the JW Marriott hotel?",
             answers: ["Parq Vancouver", "River Rock Casino Resort", "Starlight Casino", "Hard Rock Casino Vancouver"],
             correct: "Parq Vancouver"),
    Question(question: "Which casino has a Hard Rock theme and offers a large poker room?",
             answers: ["Hard Rock Casino Vancouver", "Grand Villa Casino", "Parq Vancouver", "Starlight Casino"],
             correct: "Hard Rock Casino Vancouver"),
    Question(question: "Which casino is known for its VIP gaming experience and high-limit rooms?",
             answers: ["Parq Vancouver", "Hard Rock Casino Vancouver", "River Rock Casino Resort", "Starlight Casino"],
             correct: "Parq Vancouver"),
    Question(question: "Which casino features a large variety of slot machines and electronic gaming tables?",
             answers: ["River Rock Casino Resort", "Grand Villa Casino", "Starlight Casino", "Hard Rock Casino Vancouver"],
             correct: "Grand Villa Casino"),
    Question(question: "Which casino offers live entertainment, a theater, and a hotel?",
             answers: ["Starlight Casino", "Hard Rock Casino Vancouver", "River Rock Casino Resort", "Parq Vancouver"],
             correct: "River Rock Casino Resort")
]

let quizHotelsVancouver = [
    Question(question: "Which luxury hotel in Vancouver is known for its iconic Fairmont Gold experience?",
             answers: ["Shangri-La Vancouver", "The Sutton Place Hotel", "Fairmont Pacific Rim", "JW Marriott Parq Vancouver"],
             correct: "Fairmont Pacific Rim"),
    Question(question: "Which Vancouver hotel is the tallest in the city?",
             answers: ["Shangri-La Vancouver", "Rosewood Hotel Georgia", "Fairmont Hotel Vancouver", "The Douglas, Autograph Collection"],
             correct: "Shangri-La Vancouver"),
    Question(question: "Which hotel is located at the entrance to Stanley Park and offers stunning waterfront views?",
             answers: ["Fairmont Waterfront", "Pan Pacific Vancouver", "The Westin Bayshore", "Fairmont Pacific Rim"],
             correct: "The Westin Bayshore"),
    Question(question: "Which hotel in Vancouver is famous for its five-star service and historic charm?",
             answers: ["Shangri-La Vancouver", "The Sutton Place Hotel", "Rosewood Hotel Georgia", "Fairmont Hotel Vancouver"],
             correct: "Rosewood Hotel Georgia"),
    Question(question: "Which Vancouver hotel features a rooftop pool with breathtaking city views?",
             answers: ["Fairmont Pacific Rim", "JW Marriott Parq Vancouver", "Pan Pacific Vancouver", "The Douglas, Autograph Collection"],
             correct: "JW Marriott Parq Vancouver"),
    Question(question: "Which Vancouver hotel is connected to Canada Place and offers cruise ship passengers a convenient stay?",
             answers: ["The Westin Bayshore", "Rosewood Hotel Georgia", "Fairmont Waterfront", "Pan Pacific Vancouver"],
             correct: "Pan Pacific Vancouver"),
    Question(question: "Which hotel is known for its elegant European-style decor and central location?",
             answers: ["Fairmont Hotel Vancouver", "The Sutton Place Hotel", "Shangri-La Vancouver", "JW Marriott Parq Vancouver"],
             correct: "The Sutton Place Hotel"),
    Question(question: "Which hotel offers a luxurious spa experience and is part of the Parq Vancouver entertainment complex?",
             answers: ["JW Marriott Parq Vancouver", "Fairmont Pacific Rim", "The Westin Bayshore", "Shangri-La Vancouver"],
             correct: "JW Marriott Parq Vancouver"),
    Question(question: "Which hotel is known for its exquisite fine dining restaurant, Hawksworth?",
             answers: ["Rosewood Hotel Georgia", "Shangri-La Vancouver", "The Sutton Place Hotel", "Fairmont Waterfront"],
             correct: "Rosewood Hotel Georgia"),
    Question(question: "Which Fairmont hotel in Vancouver is often called the 'Castle in the City'?",
             answers: ["Fairmont Pacific Rim", "Fairmont Hotel Vancouver", "Fairmont Waterfront", "The Douglas, Autograph Collection"],
             correct: "Fairmont Hotel Vancouver")
]

let quizRestaurantsVancouver = [
    Question(question: "Which Vancouver restaurant is famous for its seafood and waterfront views?",
             answers: ["Hawksworth Restaurant", "Miku", "Blue Water Cafe", "L'Abattoir"],
             correct: "Blue Water Cafe"),
    Question(question: "Which restaurant is known for its signature Aburi-style sushi?",
             answers: ["Blue Water Cafe", "Miku", "Chambar", "L'Abattoir"],
             correct: "Miku"),
    Question(question: "Which fine dining restaurant in Vancouver is located inside the Rosewood Hotel Georgia?",
             answers: ["Hawksworth Restaurant", "St. Lawrence", "Miku", "L'Abattoir"],
             correct: "Hawksworth Restaurant"),
    Question(question: "Which restaurant in Vancouver offers a mix of Belgian and French cuisine?",
             answers: ["Botanist", "Blue Water Cafe", "St. Lawrence", "Chambar"],
             correct: "Chambar"),
    Question(question: "Which restaurant is known for its refined take on classic French-Canadian cuisine?",
             answers: ["Hawksworth Restaurant", "Blue Water Cafe", "St. Lawrence", "L'Abattoir"],
             correct: "St. Lawrence"),
    Question(question: "Which Vancouver restaurant is famous for its creative cocktails and contemporary Pacific Northwest cuisine?",
             answers: ["Miku", "Hawksworth Restaurant", "Botanist", "Blue Water Cafe"],
             correct: "Botanist"),
    Question(question: "Which Gastown restaurant is located in a historic building and known for its modern French dishes?",
             answers: ["St. Lawrence", "Miku", "Chambar", "L'Abattoir"],
             correct: "L'Abattoir"),
    Question(question: "Which restaurant in Vancouver is known for its high-end farm-to-table dining experience?",
             answers: ["Hawksworth Restaurant", "Botanist", "Forage", "Blue Water Cafe"],
             correct: "Forage"),
    Question(question: "Which Vancouver restaurant specializes in authentic, high-quality ramen?",
             answers: ["Marutama Ramen", "Miku", "Botanist", "Forage"],
             correct: "Marutama Ramen"),
    Question(question: "Which restaurant is located inside the Fairmont Pacific Rim and offers a luxurious dining experience?",
             answers: ["Botanist", "St. Lawrence", "Blue Water Cafe", "Miku"],
             correct: "Botanist")
]

let quizAttractionsVancouver = [
    Question(question: "Which famous Vancouver park is known for its scenic seawall and lush greenery?",
             answers: ["Queen Elizabeth Park", "Stanley Park", "Lynn Canyon Park", "VanDusen Botanical Garden"],
             correct: "Stanley Park"),
    Question(question: "Which Vancouver attraction features a suspension bridge over a deep canyon?",
             answers: ["Lynn Canyon Suspension Bridge", "Sea to Sky Gondola", "Capilano Suspension Bridge", "Grouse Mountain Skyride"],
             correct: "Capilano Suspension Bridge"),
    Question(question: "Which cultural district in Vancouver is famous for its public market and artisan shops?",
             answers: ["Granville Island", "Gastown", "Chinatown", "Yaletown"],
             correct: "Granville Island"),
    Question(question: "What is the name of Vancouver's historic district known for its steam clock?",
             answers: ["Gastown", "Chinatown", "Yaletown", "West End"],
             correct: "Gastown"),
    Question(question: "Which mountain near Vancouver offers skiing, hiking, and panoramic city views?",
             answers: ["Cypress Mountain", "Whistler Mountain", "Mount Seymour", "Grouse Mountain"],
             correct: "Grouse Mountain"),
    Question(question: "Which Vancouver garden is famous for its vibrant flower displays and Bloedel Conservatory?",
             answers: ["Queen Elizabeth Park", "VanDusen Botanical Garden", "Dr. Sun Yat-Sen Classical Chinese Garden", "Stanley Park Rose Garden"],
             correct: "Queen Elizabeth Park"),
    Question(question: "Which Vancouver attraction features an underwater world with marine life exhibits?",
             answers: ["Science World", "Vancouver Aquarium", "Capilano Salmon Hatchery", "UBC Botanical Garden"],
             correct: "Vancouver Aquarium"),
    Question(question: "Which iconic stadium in Vancouver is home to the BC Lions and Vancouver Whitecaps FC?",
             answers: ["Pacific Coliseum", "BC Place", "Swangard Stadium", "Rogers Arena"],
             correct: "BC Place"),
    Question(question: "Which museum in Vancouver is dedicated to Indigenous art and culture?",
             answers: ["Museum of Anthropology", "Science World", "Vancouver Art Gallery", "Bill Reid Gallery"],
             correct: "Museum of Anthropology"),
    Question(question: "Which scenic drive connects Vancouver to Whistler with breathtaking views?",
             answers: ["Fraser Valley Highway", "Sea to Sky Highway", "Pacific Rim Highway", "Crowsnest Highway"],
             correct: "Sea to Sky Highway")
]
